name: Deploy Backend

on:
  push:
    paths:
      - "server/**"
      - "prisma/**"
      - ".github/workflows/deploy-backend.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v4.3.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: noc-adherence-api
          heroku_email: kreesangovender12@gmail.com
          appdir: server           # tells action to deploy ./server
