name: Deploy Backend

on:
  push:
    paths:
      - "server/**"
      - "prisma/**"
      - ".github/workflows/deploy-backend.yml"
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install + log in to the Heroku CLI
      - name: Set up Heroku CLI
        uses: heroku/actions/setup-heroku@v2
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}
          email:   kreesangovender12@gmail.com

      # 3) Deploy only the server/ folder (subtree push)
      - name: Deploy server folder
        run: |
          git subtree push --prefix server https://git.heroku.com/noc-adherence-api.git main
