name: Deploy Backend

on:
  push:
    paths: [ "server/**", "prisma/**" ]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v4.3.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: noc-adherence-api      # ← your real app name
          heroku_email: kreesangovender12@gmail.com
            appdir:          server         # ← ADD THIS LINE
