name: Deploy Backend

on:
  push:
    paths:
      - "server/**"
      - "prisma/**"
      - ".github/workflows/deploy-backend.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out repo ----------
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install & log-in to Heroku ----------
      - name: Set up Heroku CLI
        uses: heroku/setup-heroku@v2
        with:
          email:  kreesangovender12@gmail.com
          api_key: ${{ secrets.HEROKU_API_KEY }}

      # 3) Push only the server/ folder ----------
      - name: Deploy server/ to Heroku
        run: |
          # Create a lightweight subtree with just the server code
          git subtree push --prefix server https://git.heroku.com/noc-adherence-api.git main
